title: Coding with Shaun
description: "A blog dedicated to help the audience learn along with the authors."
url: "http://www.codingwithshaun.com"

name: Coding with Shaun
markdown: kramdown

livereload: true

permalink: pretty

navigation:
- text: Archive
  url: /

collections:
  shorts:
    output: true
    permalink: /:collection/:path/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
